appaccount/urls.py
from django.urls import path,include,reverse
from django.contrib.auth.views import LoginView, LogoutView
from appaccount.views import AccountCreateView, hello_world,AccountUserDetailView,AccountUserUpdateView,AccountUserDeleteView

#호출 쉽게 하려고 accountapp:urls
app_name="appaccount"

urlpatterns = [
   path('hello_world/',hello_world,name='hello_world'),
   path('login/', LoginView.as_view(template_name="appaccount/login.html"), name='login'),
   path('logout/', LogoutView.as_view(), name='logout'),
   path('create/',AccountCreateView.as_view(),name='create'),
   path('detail/<int:pk>', AccountUserDetailView.as_view(), name='detail'),
   path('update/<int:pk>', AccountUserUpdateView.as_view(), name='update'),
   path('delete/<int:pk>', AccountUserDeleteView.as_view(), name='delete'),
 
]

fire_situation/urls.py
from fire_situation import views
from django.urls import path

app_name="fire_situation"

urlpatterns = [
      path('',views.detail_main_page,name='situation'),
]

probono_fire/urls.py
from distributed import fire_and_forget
from django.contrib import admin
from django.urls import path,include

#이미지 url 
from django.conf.urls.static import static
from django.conf import settings

from probono_fire.views import front_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('appaccount.urls')),
    path('',front_page,name='front'),
    path('fire/',include('fire_situation.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

appaccount/models.py
from django.db import models


# Create your models here.

#db
class HelloWorld(models.Model):
    text=models.CharField(max_length=255,null=False)

fire_situation/models.py
from django.db import models

# Create your models here.

appaccount/forms.py
from multiprocessing import AuthenticationError
from django import forms
from django.contrib.auth.forms import UserCreationForm

# 유저 정보 변경
class AccountUserUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #입력 불가능
        self.fields['username'].disabled = True
        #help_text
        self.fields['username'].help_text = "아이디는 변경 불가능 합니다"
        self.fields['password1'].help_text = "특수문자,숫자,문자 모두 포함해야 합니다"
        self.fields['password2'].help_text = "패스워드를 다시 입력하세요"
        #rename
        self.fields['username'].label="아이디"
        self.fields['password1'].label="패스워드"
        self.fields['password2'].label="패스워드확인"
        
class AccountUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #help_text
        self.fields['username'].help_text = ""
        self.fields['password1'].help_text = "특수문자,숫자,문자 모두 포함해야 합니다"
        self.fields['password2'].help_text = "패스워드를 다시 입력하세요"
        #rename
        self.fields['username'].label="아이디"
        self.fields['password1'].label="패스워드"
        self.fields['password2'].label="패스워드확인"
        
   
class LoginForm(AuthenticationError):
    answer = forms.IntegerField(help_text='3 + 3 = ?')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #help_text
        self.fields['username'].help_text = ""
        self.fields['password1'].help_text = "특수문자,숫자,문자 모두 포함해야 합니다"
        self.fields['password2'].help_text = "패스워드를 다시 입력하세요"
        #rename
        self.fields['username'].label="아이디"
        self.fields['password1'].label="패스워드"
        self.fields['password2'].label="패스워드확인"
    def clean_answer(self): # 회원가입 벨리데이션 추가
        answer = self.cleaned_data.get('answer')
        if answer != 6:  
            raise forms.ValidationError('땡~')
        return answer

appaccount/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy

from appaccount.models import HelloWorld

# Create your views here.
from django.views.generic import CreateView,DetailView,UpdateView,DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from appaccount.forms import AccountUserCreationForm, AccountUserUpdateForm


def hello_world(request):
    #return HttpResponse('히히')
    
    if request.method=="POST":
        #요청을 받은 메소드가 post일 경우 아래 html을 리턴한다.
        temp=request.POST.get('hello_world_input')
    
        new_hello_world=HelloWorld()
        new_hello_world.text=temp
        new_hello_world.save()
        
        return HttpResponseRedirect(reverse('appaccount:hello_world'))
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request,'appaccount/sub_page.html',context={'hello_world_list': hello_world_list})


        
class AccountCreateView(CreateView):
    
    model = User
    form_class = AccountUserCreationForm
    success_url = reverse_lazy('appaccount:hello_world')
    template_name = 'appaccount/account_user.html'


class AccountUserDetailView(DetailView):
    model = User
    context_object_name = 'user_name'
    form_class = UserCreationForm
    template_name = 'appaccount/account_user_detail.html'
    
class AccountUserUpdateView(UpdateView):
    model = User
    context_object_name = 'user_name'
    form_class = AccountUserUpdateForm
    success_url = reverse_lazy('appaccount:hello_world')
    template_name = 'appaccount/account_user_update.html'
    
class AccountUserDeleteView(DeleteView):
    model = User
    context_object_name = 'user_name'
    success_url = reverse_lazy('appaccount:login')
    template_name = 'appaccount/account_user_delete.html'
 

fire_situation/views.py
from django.shortcuts import render

# Create your views here.

def detail_main_page(request):
    return render(request,'detail_main_page.html')

probono_fire/views.py
from django.shortcuts import render


def front_page(request):
    #return HttpResponse('히히')
    return render(request,'front_page.html')

appaccount/templates/appaccount/account_user.html
{% extends 'main_page.html' %}

{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 1rem auto; ">
        <div class="mb-4">
            <h4 style="font-family: 'EF_WAKEUP';" >
                회원가입
            </h4>
        </div>
        <form action="{% url 'appaccount:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            
            <input type="submit" class="btn btn-dark rounded-pill col-6" style="font-family: 'EF_WAKEUP';">
        </form>
    </div>

{% endblock %}

appaccount/templates/appaccount/account_user_delete.html
{%  extends 'main_page.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4 pt-0 pb-4" style="font-family: 'EF_WAKEUP';">
        <h4>관리자 회원 탈퇴</h4>
    </div>

    <div class="jumbotron pt-3 pb-4" style="text-align: left;">
        <p class="pt-3" style="margin-bottom: 1rem; font-size: 1.4rem;text-align:center;font-family: 'GangwonEduPowerExtraBoldA';">
            탈퇴 전 확인하세요</p>
        <div class="jumbotron pt-3 pb-1"  style="background-color:#ffffff;">
            <div>
                <p class="text_p">탈퇴하시면 이용 중인 시스템과 계정이 삭제 되며 모든 내역은 복구가 불가능합니다.</p>
                <p class="text_p">제출을 누르시면 탈퇴가 완료됩니다.</p>
                <p class="text_p">본 서비스가 도움이 되셨길 바랍니다.</p>
            </div>
        </div>
        <div class="pt-0 pb-1">
        {% if Post.important is True %}
            <label> 
            <input type = "checkbox" name = "important" value ="True" checked> 안내사항을 이해하였으며 주의사항을 확인하였습니다</label> 
        {% else %}
            <label> <input type = "checkbox" name = "important" value = "False"> 안내사항을 이해하였으며 주의사항을 확인하였습니다<br>
            </label> 
        {% endif %}
        </div>
    </div>
        <form action="{% url 'appaccount:delete' pk=user_name.pk %}" method="post">
            {%  csrf_token %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4"  style="font-family: 'EF_WAKEUP';">
        </form>
    </div>
{% endblock %}

appaccount/templates/appaccount/account_user_detail.html
{% extends 'main_page.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 2rem auto">
        <p>
            {{ user_name.date_joined }}
        </p>
        <p>
            {{ user_name.username }}
        </p>
        {% if user_name == user %}
        <a id="nav_var" href="{% url 'appaccount:update' pk=user_name.pk %}">
            <p style="font-family: 'EF_WAKEUP';">
                관리자 정보 변경
            </p>
        <a id="nav_var" href="{% url 'appaccount:delete' pk=user_name.pk %}">
            <p style="font-family: 'EF_WAKEUP';">
                관리자 회원 탈퇴
            </p>
        </a>
        {% endif %}
        
    </div> 

{% endblock %}

appaccount/templates/appaccount/account_user_update.html
{%  extends 'main_page.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4" style="font-family: 'EF_WAKEUP';">
        <h4>관리자 정보 변경</h4>
    </div>
        <form action="{% url 'appaccount:update' pk=user_name.pk %}" method="post">
            {%  csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" style="font-family: 'EF_WAKEUP';">
        </form>
    </div>
{% endblock %}

appaccount/templates/appaccount/login.html
{% extends 'main_page.html'%}
{%load bootstrap4%}
{% block content %}

    <div style="text-align: center">
        <div class="login_out" style="font-family: 'EF_WAKEUP';">
            <h4>로그인</h4>
        </div>
        <div class="login_out">
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-2"  style="font-family: 'EF_WAKEUP';">
            </form>
        </div>

    </div>

{% endblock %}

appaccount/templates/appaccount/sub_page.html
{% extends 'main_page.html'%}

{% block content%}

<div style=" border-radius: 1rem; margin: 2rem; text-align:center">
    <h3 style="padding:2rem">
        Body
    </h3>
  
   
    <form action= "/account/hello_world/" method=post> 
       <!-- post란 method를 통해서 링크로 보내줌-->
        {% csrf_token %}<!-- 항상 써야함-->
        <div>
            <input type="text" name="hello_world_input">
        </div>

        <input  type="submit" class="btn btn-primary" value="POST">

    </form> <!-- 서버에 보내는 요청명세서 같은 역할 views.py에 잘 적혀 있음-->


    {% if hello_world_list %} 
        {% for hello_world in hello_world_list %}
        <h6>
            {{hello_world.text}}
        </h6>
        {% endfor %}
    {% endif %}

</div>


{% endblock %}

fire_situation/templates/detail_main_page.html
{% extends 'main_page.html'%}
{%load bootstrap4%}
{% block content %}


<div>
    안내내용
</div>
{% endblock %}

templates/footer.html
<div class="main_footer">
    
    <div style="font-size:1rem; margin-top:2rem;">
       <p class='mt-4'>시각 장애인을 위한 화재대피 관리자 시스템<p>
    </div>
    <div>    
        <p>최혜린, 고정주, 박예찬, 전상철</p>
    </div>

</div>

templates/front_page.html
{% extends 'main_page.html'%}
{%load bootstrap4%}
{% block content %}


<div style="text-align: center; max-width: 500px; margin: 1rem auto; ">
    
    
    <form action="" method="post">
        {% csrf_token %}

    </form>
</div>
<div >
    <img class="white_Cane_image" src="/probono_fire/static/img/white_cane.png" alt="white_cane">
</div>
{% endblock %}

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HHT 시각장애인을 위한 화재대피 관리자 시스템</title>

    <link rel="stylesheet" type="text/css" href="{% static 'main_page.css' %}">

</head>

templates/header.html
<!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<div style = "text-align:center;margin-top:1rem;margin-bottom:0.5rem;">
    <div class=main_header_title>

        <div class=main_header_title_name>
        <div>
            <a style="font-size:2.5rem;">HHT</a>
        </div>
        </div>

    </div>
</div>

<div style = "text-align:center;margin-top:0.4rem;">
        <a id="nav_var" href="{% url 'front' %}?next={{ request.path }}">
        <span>서비스소개</span> |
        </a>
        {% if not user.is_authenticated %}
        <a id="nav_var" href="{% url 'appaccount:login' %}?next={{ request.path }}">
            <span>로그인</span> |
        </a>
        <a id="nav_var" href="{% url 'appaccount:create' %}?next={{ request.path }}">
            <span>회원가입</span>
        </a>
        {% else %}
        <a id="nav_var" href="{% url 'fire_situation:situation' %}?next={{ request.path }}">
            <span>화재상황</span> |
        </a>
        <a id="nav_var" href="{% url 'appaccount:detail' pk=user.pk %}">
            <span>회원정보확인</span> |
        </a>
        <a id="nav_var" href="{% url 'appaccount:logout' %}?next={{ request.path }}">
            <span>로그아웃</span>
        </a>
        {% endif%}
    </div>

</div>

templates/main_page.html
<!DOCTYPE html>
<html lang="en">

{%include 'head.html'%}

<body>
    {% include 'header.html' %}
    <hr>

    {% block content %}
    {% endblock %}
    <hr>
    
    {% include 'footer.html' %}

    
  </body>

</html>